/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/url": {
    post: operations["UrlController_createUrl"];
  };
  "/url/{shorturl}": {
    get: operations["UrlController_getUrl"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UrlGetDto: {
      /** @description url */
      url: string;
    };
    CreateShortUrlResponseDto: {
      /** @description url */
      _id: string;
      /** @description url */
      url: string;
      /** @description shorturl */
      shorturl: string;
      /** Format: date-time */
      created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_getHello: {
    responses: {
      /** @description Hello World! */
      200: {
        content: never;
      };
    };
  };
  UrlController_createUrl: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UrlGetDto"];
      };
    };
    responses: {
      /** @description The short url has been successfully created. */
      201: {
        content: {
          "application/json": components["schemas"]["CreateShortUrlResponseDto"];
        };
      };
    };
  };
  UrlController_getUrl: {
    parameters: {
      path: {
        shorturl: string;
      };
    };
    responses: {
      /** @description The url has been successfully retrieved. */
      200: {
        content: {
          "application/json": components["schemas"]["UrlGetDto"];
        };
      };
    };
  };
}
